import Head from "next/head";
import Footer from "@/common/components/Footer";
import Navbar from "@/common/components/Navbar";

export default function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>Ifrat;</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="root-layout">
        <Navbar />
        <main className="main-container">{children}</main>
        <Footer />
      </div>
    </>
  );
}
